### ISSUE TITLE
Provide price pallet for Antimatter ecology

### ISSUE THREAD

**Issue by armatrix** [antimatter-dao/polka-pallet#1]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Provide price pallet for Antimatter ecology

**Describe the feature you'd like:**
In the asset pool, the price of the relevant assets needs to be obtained when the liquidation business is performed. This commit will contain a basic price capture module.

**Describe alternatives you've considered:**
1. Obtain price data from mainstream exchanges
2. Adapt Chainlink to obtain price data on the chain

**Comment by 4his2** [comment]
Need to impl OCW to obtain price in the next stage.
